E2082. Track time between successive tag assignments
expertiza/expertiza pull request #1929
Opened 2021-04-14 18:25 UTC by Sichao25

Please set the title of your pull request in the following format: `[Project id/Independent study/Issue fix/...]. project name`, eg., `E904. Integrating courses and assignments on Expertiza with Moodle`

We suggest you including the below information in your pull request:
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.
---
About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

2021-04-14 23:45 UTC, johnbumgardner requested changes
in addition to these changes please fix whitespace and bracketting. Ruby doesnt always require {} for if and else, so please remove to increase code readability.

Overall, looks good. Maybe add another Rspec test or two, and correct the comments I left

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    intervals = intervals.select{|v| v < threshold}
add spaces between  the brackets to make it look like 
```intervals = intervals.select{ |v| v < threshold }```

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    if not intervals.empty?
use unless instead of if not

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    #build the parameters for the chart
add space between  # and comment

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    if not intervals.empty?
use unless instead of if not

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +        labels: [*1..intervals.length],
move the hash entry two spaces right relative to the the left curly bracket

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +            if not intervals.empty?
use unless instead of if not

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +  #Calculate mean, min, max, variance, and stand deviation for tagging intervals
add space between comment and text

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +  def calculate_key_chart_information(intervals)
use more Ruby like function naming convention
```calculate_key_chart_information``` should be ```key_chart_info```

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    interval_precision = 2 #Round to 2 Decimal Places
add space between # and comment text

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    intervals = intervals.select{|v| v < threshold}
add spaces in {} - same issue as before

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    #Get Metrics once tagging intervals are available
space between # and comment text

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +      metrics = Hash.new
use 
```metric = {}```

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +      sum = intervals.inject(0){|accum, i| accum +(i- metrics[:mean])**2}
surround operands with spaces
add spaces around the curly

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +      metrics[:variance] = (sum/(intervals.size).to_f).round(interval_precision)
add spaces to surround ```/```
change ```(intervals.size).to_f```
to ```interval.size.to_f```

2021-04-14 23:45 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +    #if no Hash object is returned, the UI handles it accordingly
space between # and comment text

2021-04-14 23:45 UTC, johnbumgardner commented on app/models/tag_prompt_deployment.rb
> +          for i in 1..(number_of_updated_time -1) do
use each instead of for --- better convention for ruby

2021-04-14 23:45 UTC, johnbumgardner commented on app/models/tag_prompt_deployment.rb
> +            tag_update_intervals.append(tag_updated_times[i] - tag_updated_times[i-1])
change to this
```tag_updated_times[i - 1]```

2021-04-14 23:45 UTC, johnbumgardner commented on app/models/tag_prompt_deployment.rb
> +          answer_tagging = VmUserAnswerTagging.new(user, answers.count, answers_inferred_by_ml.count, taggable_answers.count, tags.count, not_tagged_answers.count, percentage, tag_update_intervals)
shorten this line if you can for readability

2021-04-14 23:45 UTC, johnbumgardner commented on spec/helpers/review_mapping_helper_spec.rb
> +
delete

2021-04-14 23:45 UTC, johnbumgardner commented on spec/helpers/review_mapping_helper_spec.rb
> +      intervals = [1.00,2.00,3.00,4.00,5.00,6.00]
add spaces between the commas so i can read the test easier

2021-04-20 05:17 UTC, Winbobob commented on spec/helpers/review_mapping_helper_spec.rb
> +require 'spec_helper'
You do not need to require this help since it has been required.

2021-04-20 19:40 UTC, johnbumgardner approved these changes
Looks good to me @Sichao25

2022-02-01 21:34 UTC, closed without merging