E2112. Integrate Suggestion Detection Algorithm
expertiza/expertiza pull request #1952
Opened 2021-04-27 05:28 UTC by harshkachhadia

This amendment to the project involves integration of API calls for review metrics such as Suggestion Detection, Problem Detection and Sentiment Analysis. 

In a response form, we have included a "Generate Review Metrics" button, on click of which, the reviewer will get the review metrics for all his response comments in a tabular format.

**NOTE:** As the APIs are from the VCL Deployment of NLP Review Metrics, the calls are taking longer than usual times and so, expect a wait for them. Also, the total time taken for table generation(along with all API calls) is displayed in "seconds" under the table.

-@efg, @johnbumgardner 

**Bug Report:** In the response form on beta branch, the html tag ids are uneven for response text boxes, which creates a lot of problems for developers,  and we accounted for this in our implementation, in which we need to make minor modification in javascript code to accommodate the correction. **NOTE:**(This bug has been solved on the production version of expertiza, but still needs to be fixed on the beta branch version of expertiza.)

2021-04-27 15:36 UTC, johnbumgardner requested changes

2021-04-27 15:36 UTC, johnbumgardner commented on app/views/response/_response_analysis.html.erb
> +<!DOCTYPE html>
add coloring based on positive and negative (green and red)
add hover effects to explain what the metrics are.
add configurable text file to let professor set preferences for what metrics are being used

2021-04-27 15:36 UTC, johnbumgardner commented on app/views/response/_response_analysis.html.erb
> +            console.log("value of j");
i dont think we want logging on the version we merge into beta

2021-04-27 15:36 UTC, johnbumgardner commented on app/views/response/_response_analysis.html.erb
> +    <title>Convert JSON Data to HTML Table</title>
since you used something you didn't write here, please add a comment with where this comes from so future developers can maintain the code easier

2021-04-27 15:36 UTC, johnbumgardner commented on app/views/response/_response_analysis.html.erb
> +           for (var i =2; i < (j); i++) {
there may be a reason we use var here, but i think let is safer. make sure this is the correct way to do it

2021-04-27 15:36 UTC, johnbumgardner commented on app/views/response/_response_analysis.html.erb
> +            console.log(reviews);
why are we logging

2021-04-27 15:36 UTC, johnbumgardner commented on app/models/metric.rb
> +#     https://peerlogic.csc.ncsu.edu/sentiment/analyze_reviews_bulk
make these comments consistent

2021-04-27 15:36 UTC, johnbumgardner commented on app/models/metric.rb
> +
fix whitespace. way too much

2021-04-27 15:36 UTC, johnbumgardner commented on app/models/metric.rb
> +
whitespace

2021-04-27 15:36 UTC, johnbumgardner commented on app/models/metric.rb
> +  rescue StandardError
is there not a more descriptive error than StandardError

2021-04-27 15:36 UTC, johnbumgardner commented on app/models/metric.rb
> +
eeek whitespace

2021-04-27 15:36 UTC, johnbumgardner commented on db/schema.rb
> -    t.integer  "version_num",        limit: 4
is there a migration file that is causing these changes

2021-04-27 21:03 UTC, johnbumgardner reviewed
LGTM - hopefully i can get the gemfiles working so yall can get that check laster

2021-04-28 04:50 UTC, johnbumgardner commented on Gemfile.lock
> +<<<<<<< HEAD
fix merge conflict and repush

2021-04-29 15:54 UTC, harshkachhadia reviewed
All the changes requested by @johnbumgardner have been made in the code. Thank you pointing them out.

2021-04-29 16:00 UTC, johnbumgardner requested changes
Needs Rspec tests. Will Travis fail to build without the Gemfile changes?

2021-04-29 18:44 UTC, johnbumgardner requested changes

2021-04-29 18:44 UTC, johnbumgardner commented on spec/controllers/response_controller_spec.rb
> +        expect(fetch_review_metric).not_to be_nil
very shallow test. make sure the yml file is read with what you expect it to be

2021-04-29 20:01 UTC, johnbumgardner commented on spec/controllers/response_controller_spec.rb
> +        expect(fetch_review_metric).not_to be_nil
metrics = fetch_review_metric #["sentiment","problem","suggestion"], ["sentiment"], []
expect(metrics.length) to be <= 3
metrics.each do |metric|
expect(["sentiment","problem","suggestion"].include? metric).to eq(true)
end

2021-04-30 17:30 UTC, harshkachhadia reviewed
> indent the expect

Done.

2021-07-11 21:30 UTC, Winbobob commented
/cancel d699 c51d

2021-07-11 21:41 UTC, closed without merging