Rubrics tab weight check
expertiza/expertiza pull request #2034
Opened 2021-09-04 20:43 UTC by nnhimes

PR to check the weight of questions in a rubric and flash a warning if the weight is 0 (has no ScoredQuestions). 
For Johns issue #2023 

Not ready as of 9-4. 
![image](https://user-images.githubusercontent.com/41524135/132107486-9cdd4bbc-3bca-481f-9169-93c53c9218d3.png)

Changing the review rubric to my 9-1-21 Test, which one has a section header inside it, does not give my flash warning. May be because the flash[:note] = 'The assignment was successfully saved....' is called immediately after in update_feedback_attributes(). 

Is there a way to flash two messages at once?

2021-09-05 17:02 UTC, johnbumgardner requested changes

2021-09-05 17:02 UTC, johnbumgardner commented on app/controllers/assignments_controller.rb
> +        flash[:error] = "A rubric has no ScoredQuestions, but still has a weight. Please change the weight to 0."
make this a flash note instead of an error to show simultaneously

2021-09-05 17:02 UTC, johnbumgardner commented on app/models/assignment_form.rb
> +      unless scored_questionnaire || assignment_questionnaire[:questionnaire_weight].to_i == 0
instead of == 0, use .zero?

2021-09-05 21:16 UTC, nnhimes commented
Working now, though an unrelated bug was found - adding to issues
![image](https://user-images.githubusercontent.com/41524135/132141656-4a5dd619-9ee1-4762-a2ba-ea8d0a6ad9ed.png)
![image](https://user-images.githubusercontent.com/41524135/132141671-75f9e746-08b0-411b-acb5-04d6b0cacdfc.png)

2021-09-12 21:01 UTC, johnbumgardner approved these changes

2021-09-14 03:38 UTC, merged