Assignment helper compute refactor
expertiza/expertiza pull request #2050
Opened 2021-09-26 18:51 UTC by nnhimes

We talked about reducing the assignment_helper methods dependence on assignment in our 9-22 meeting. This PR removes all self calls in the methods and allows them to be called outside of assignment now (usually by including assignment as a parameter). 

Did not move these out of assignment_helper because the three main methods to refactor depend heavily on private methods that would need to be copy pasted otherwise. Also, there is no one place that called assignment.method, it was split between assignment_team, response_map, report_formatter_helper, and a handful of spec files.

2021-09-27 03:39 UTC, johnbumgardner requested changes
There are quite a few Travis CI failures. Please correct them.

2021-09-27 03:39 UTC, johnbumgardner commented on app/models/response_map.rb
> +    scores[:total_score] = AssignmentHelper.compute_total_score(assignment, scores)
can you include assignment helper and not need to actually call it as AssignmentHelper?

2021-09-27 03:39 UTC, johnbumgardner commented on app/models/response_map.rb
> +    scores[:total_score] = AssignmentHelper.compute_total_score(assignment, scores)
+1

2021-09-27 03:39 UTC, johnbumgardner commented on spec/controllers/grades_controller_spec.rb
> +        allow_any_instance_of(AssignmentHelper).to receive(:compute_total_score).with(any_args).and_return(100)
not familiar with this syntax.

2021-11-02 19:36 UTC, nnhimes commented
No obvious fix still, not sure how to get this refactor working - especially when the includes/requires are not working as expected. May need to close the PR and start from scratch

2021-11-14 19:51 UTC, nnhimes commented
Making a new fresh attempt, too many commits here

2021-11-14 19:51 UTC, closed without merging