E2165 Fix teammate-review view
expertiza/expertiza pull request #2138
Opened 2021-11-13 23:23 UTC by Arvasu

Proposed changes can be found in the documentation link below:
- https://expertiza.csc.ncsu.edu/index.php/CSC/ECE_517_Fall_2021_-_E2165._Fix_teammate-review_view
- Contributor usernames: Anjali, Arvasu, Lalit, Vinay

2022-01-30 21:40 UTC, nnhimes commented
I need to do manual testing now before it merge

2022-01-30 21:51 UTC, johnbumgardner requested changes
make changes and manual test.

2022-01-30 21:51 UTC, johnbumgardner commented on app/views/grades/_add_icon_to_name.html.erb
> +  <% fullname = Participant.find_by(id: reviewer_id).fullname(session[:ip]) %>
lines 1 through 14 should really be done in whatever controller calls this

2022-01-30 21:51 UTC, johnbumgardner commented on app/views/grades/view_team.html.erb
> +    const revieweeIdToShow= selectNode.value;
```suggestion
    const revieweeIdToShow = selectNode.value;
```

2022-01-30 21:51 UTC, johnbumgardner commented on app/views/grades/_add_icon_to_name.html.erb
> +<% if @current_role_name.eql?'Student' or questionnaire_type != "TeammateReviewQuestionnaire" %>
```suggestion
<% if @current_role_name.eql?'Student' || questionnaire_type != "TeammateReviewQuestionnaire" %>
```

2022-01-31 15:43 UTC, johnbumgardner commented
This seems busted still.

I am going to close this Pull Request. Functionality is not here.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/38589044/151825034-9d16fc3a-8cb7-405e-a970-29002fd58806.png">

2022-01-31 15:43 UTC, closed without merging