Fix Rubocop Scope Problem
expertiza/expertiza pull request #2249
Opened 2022-02-13 21:40 UTC by nnhimes

To make rubocop only run on changed files in a PR

2022-02-15 18:10 UTC, nnhimes commented
Check https://docs.rubocop.org/rubocop/cops.html for any more cops that should be added. We can either make the fixes ~100-200 in this PR or make a new one

2022-02-16 18:09 UTC, johnbumgardner requested changes

2022-02-16 18:09 UTC, johnbumgardner commented on app/models/quiz_response_map.rb
> +    weighted_quiz_score
```suggestion

    weighted_quiz_score = calculated_score[0].graded_percent.to_f.round(1)
    weighted_quiz_score
```
```suggestion
    calculated_score[0].graded_percent.to_f.round(1)
```

2022-02-16 18:09 UTC, johnbumgardner commented on app/models/quiz_response_map.rb
> +    weighted_quiz_score
stop using the weighted quiz score

2022-02-16 18:09 UTC, johnbumgardner commented on app/models/review_response_map.rb
> +    reviewer_is_team
```suggestion
    reviewer_is_team
```
```suggestion

```

2022-02-16 18:09 UTC, johnbumgardner commented on app/models/review_response_map.rb
>      reviewer_is_team = assignment.reviewer_is_team
```suggestion
    reviewer_is_team = assignment.reviewer_is_team
```
```suggestion
    assignment.reviewer_is_team
```

2022-02-17 20:16 UTC, merged