E2229 Track the time students look at other submissions
expertiza/expertiza pull request #2377
Opened 2022-04-17 21:53 UTC by Jmanderson1997

Please set the title of your pull request in the following format: `[Project id/Independent study/Issue fix/...]. project name`, eg., `E904. Integrating courses and assignments on Expertiza with Moodle`

We suggest you including the below information in your pull request:
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.
---
About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

2022-04-19 15:08 UTC, johnbumgardner requested changes

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +<% def get_link_round_review_time(map_id, round, link) %>
functions should not be defined in views

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +  <% reviewee_list = Array.new %>
```suggestion
  <% reviewee_list = [] %>
```

use this syntax when you don't initialize the array to anything specific

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +  <% total_time_list = Array.new %>
```suggestion
  <% total_time_list = [] %>
```

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +  <% timeHash = Hash.new %>
```suggestion
  <% time_hash = {} %>
```

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +                <% if @count == 0 %>  <!--- print revieweeId,time, round only for the first row-->
```suggestion
                <% if @count.zero?%>  <!--- print revieweeId,time, round only for the first row-->
```

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +            <% @count=@count+1 %>
use each_with_index to manage counters

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +                <% if @count == 0 %>
```suggestion
                <% if @count.zero? %>
```

2022-04-19 15:08 UTC, johnbumgardner commented on app/views/popup/reviewer_details_popup.html.erb
> +    <% @reviewers = Participant.where(user_id: @user.id) %>
why are these using the @ symbol

2022-04-19 15:08 UTC, johnbumgardner commented on app/helpers/review_mapping_helper.rb
> +  def get_time_spent_on_review_for_certain_team_for_each_round(map_id)
this name is too long. also dont use 'get' in ruby

2022-04-25 18:30 UTC, LeooHsiang commented
We are building on the Previous team's implementation, E1989. Their solution wrote to the database often and did not optimize storage space to the desired metric.

We have implemented a solution by using the built-in function of pstore to mitigate database interaction and reduce the number of entries in the database significantly.

2022-04-30 18:00 UTC, closed without merging