E2241 Heatgrid fixes and improvements
expertiza/expertiza pull request #2380
Opened 2022-04-19 19:24 UTC by EshwarCVS

E2241/Heatgrid fixes and improvements/Issue#1869

Changes made:

- Removed countofcomments attribute from vm_question_response_row.rb file.
- Added metric_hash attribute to store the metric values for each response in vm_question_response_row.rb.
- Iterate values in metric_hash in view_team.html.erb file to show the metric values in the heat grid.
- Added a new method calculate_metrics, that calls all other methods for different metric calculations.

Mentioning the contributors as we have done peer programming:
@EshwarCVS
@gokul-koganti
@J-Sumer
@sbosenc

2022-04-21 03:15 UTC, johnbumgardner requested changes
make changes

2022-04-21 03:15 UTC, johnbumgardner commented on app/models/vm_question_response.rb
> +          row.metric_hash["countofcomments"] = 0 if row.metric_hash["countofcomments"] == nil
```suggestion
          row.metric_hash["countofcomments"] = 0 if row.metric_hash["countofcomments"].nil?
```

2022-04-21 03:15 UTC, johnbumgardner commented on app/models/vm_question_response.rb
> +          row.metric_hash["countofcomments20"] = 0 if row.metric_hash["countofcomments20"] == nil
```suggestion
          row.metric_hash["countofcomments20"] = 0 if row.metric_hash["countofcomments20"].nil?
```

2022-04-21 03:15 UTC, johnbumgardner commented on app/views/grades/view_team.html.erb
> +        <% vm.list_of_rows[0].metric_hash.each do |key, value| %>
```suggestion
        <% vm.list_of_rows.first.metric_hash.each do |key, value| %>
```

2022-04-21 03:15 UTC, johnbumgardner commented on app/views/grades/view_team.html.erb
> +              <% vm.list_of_rows[0].metric_hash.each do |key, value| %>
```suggestion
              <% vm.list_of_rows.first.metric_hash.each do |key, value| %>
```

2022-04-22 17:07 UTC, J-Sumer commented on app/models/vm_question_response.rb
> +          row.metric_hash["countofcomments"] = 0 if row.metric_hash["countofcomments"] == nil
Changes are done.

2022-04-22 17:07 UTC, J-Sumer commented on app/models/vm_question_response.rb
> +          row.metric_hash["countofcomments20"] = 0 if row.metric_hash["countofcomments20"] == nil
Changes are done.

2022-04-22 17:07 UTC, J-Sumer commented on app/views/grades/view_team.html.erb
> +        <% vm.list_of_rows[0].metric_hash.each do |key, value| %>
Changes are done.

2022-04-22 17:07 UTC, J-Sumer commented on app/views/grades/view_team.html.erb
> +              <% vm.list_of_rows[0].metric_hash.each do |key, value| %>
Changes are done.

2022-04-24 18:33 UTC, nnhimes commented on app/models/vm_question_response.rb
> +          row.metric_hash["comments #10"] = 0 if row.metric_hash["comments #10"].nil?
Change string to "> 10 Word Comments" maybe, or at least capitalize what you have. Its not obvious what this means

2022-04-24 18:35 UTC, nnhimes commented
Fix rubocop and linting issues

2022-05-04 02:45 UTC, merged